// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/lanej/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetArrayEnum implements getArrayEnum operation.
//
// GET /array-enum
func (UnimplementedHandler) GetArrayEnum(ctx context.Context) (r ArrayEnum, _ error) {
	return r, ht.ErrNotImplemented
}

// GetObjectEnum implements getObjectEnum operation.
//
// GET /object-enum
func (UnimplementedHandler) GetObjectEnum(ctx context.Context) (r ObjectEnum, _ error) {
	return r, ht.ErrNotImplemented
}
